[default.extend-words]
iin = "iin"
Iin = "Iin"
IIN = "IIN"
iins = "iins"
Iins = "Iins"
IINS = "IINS"
rto = "rto"
RTO = "RTO"
OTPs = "OTPs"
vas = "vas"
ful = "ful"
utr = "utr"
UTR = "UTR"
recon = "recon"
Recon = "Recon"
tnc = "tnc"
Tnc = "Tnc"
TNC = "TNC"
whsec = "whsec"
plink = "plink"
rfnd = "rfnd"
disp = "disp"
inv = "inv"
rcpt = "rcpt"
rzp = "rzp"
RZP = "RZP"
